"""Array-independent semantic values."""

from .axes import DomainAxis, MeshAxis, MeshCoordinate, MeshTopology
from .boundaries import VerticalBoundary
from .fields import AddressableField, Field
from .grid import UniformGrid
from .locations import CELL, ZFACE, Cell, Location, ZFace
from .markers import (
    Accepted,
    Candidate,
    Divergence,
    Evaluated,
    LasdTrajectoryXVelocity,
    LasdTrajectoryYVelocity,
    LasdTrajectoryZVelocity,
    MomentumLasdCoefficient,
    MomentumLasdLm,
    MomentumLasdMm,
    MomentumLasdNn,
    MomentumLasdQn,
    PassiveScalarConcentration,
    PassiveScalarTendency,
    PressureCorrection,
    PressureRhs,
    PotentialTemperaturePerturbation,
    PotentialTemperatureTendency,
    Projected,
    ScalarLasdCoefficient,
    ScalarLasdLm,
    ScalarLasdMm,
    ScalarLasdNn,
    ScalarLasdQn,
    VerticalPressureGradient,
    VerticalVelocity,
    VerticalVelocityTendency,
    XPressureGradient,
    XVelocity,
    XVelocityTendency,
    YPressureGradient,
    YVelocity,
    YVelocityTendency,
)
from .ownership import (
    DistributionSpec,
    EqualZSlab,
    GlobalTestRegion,
    OwnedInterval,
    OwnedRegion,
    Partitioned,
    Replicated,
)
from .scales import BoussinesqScaleSystem, PassiveScalarScaleSystem, ScaleSystem
from .time import AcceptedClock, EvaluationTime

__all__ = [
    "CELL",
    "ZFACE",
    "AddressableField",
    "Accepted",
    "AcceptedClock",
    "BoussinesqScaleSystem",
    "Candidate",
    "Cell",
    "DistributionSpec",
    "Divergence",
    "DomainAxis",
    "EqualZSlab",
    "Evaluated",
    "EvaluationTime",
    "Field",
    "GlobalTestRegion",
    "LasdTrajectoryXVelocity",
    "LasdTrajectoryYVelocity",
    "LasdTrajectoryZVelocity",
    "Location",
    "MeshAxis",
    "MeshCoordinate",
    "MeshTopology",
    "OwnedInterval",
    "OwnedRegion",
    "MomentumLasdCoefficient",
    "MomentumLasdLm",
    "MomentumLasdMm",
    "MomentumLasdNn",
    "MomentumLasdQn",
    "PassiveScalarConcentration",
    "PassiveScalarScaleSystem",
    "PassiveScalarTendency",
    "Partitioned",
    "PressureCorrection",
    "PressureRhs",
    "PotentialTemperaturePerturbation",
    "PotentialTemperatureTendency",
    "Projected",
    "Replicated",
    "ScaleSystem",
    "ScalarLasdCoefficient",
    "ScalarLasdLm",
    "ScalarLasdMm",
    "ScalarLasdNn",
    "ScalarLasdQn",
    "UniformGrid",
    "VerticalBoundary",
    "VerticalPressureGradient",
    "VerticalVelocity",
    "VerticalVelocityTendency",
    "XPressureGradient",
    "XVelocity",
    "XVelocityTendency",
    "YPressureGradient",
    "YVelocity",
    "YVelocityTendency",
    "ZFace",
]
