"""Direct finite-volume numerical API and packaged simulation services.

Exports are lazy so configuration and CLI discovery do not initialize JAX.
"""
from importlib import import_module

_EXPORTS = {
    "MannBox": "jaxwind.inflow",
    "generate_mann_box": "jaxwind.inflow",
    "build_mann_inflow": "jaxwind.inflow",
    "UniformGrid": "jaxwind.domain",
    "AtmosphericSolution": "jaxwind.abl",
    "build_adaptive_atmospheric_run": "jaxwind.abl",
    "build_atmospheric_run": "jaxwind.abl",
    "build_atmospheric_step": "jaxwind.abl",
    "initial_atmospheric_solution": "jaxwind.abl",
    "LinearBoussinesqBuoyancy": "jaxwind.buoyancy",
    "boussinesq_tendency": "jaxwind.buoyancy",
    "SubgridCooling": "jaxwind.cooling",
    "SubgridSpray": "jaxwind.cooling",
    "build_subgrid_cooling_source": "jaxwind.cooling",
    "build_subgrid_spray_sources": "jaxwind.cooling",
    "atmospheric_history_diagnostics": "jaxwind.diagnostics",
    "atmospheric_profile_diagnostics": "jaxwind.diagnostics",
    "FlowModel": "jaxwind.numerics.integrate",
    "Solution": "jaxwind.numerics.integrate",
    "build_adaptive_run": "jaxwind.numerics.integrate",
    "build_run": "jaxwind.numerics.integrate",
    "build_step": "jaxwind.numerics.integrate",
    "build_tendency": "jaxwind.numerics.integrate",
    "initial_solution": "jaxwind.numerics.integrate",
    "IdealGasMixture": "jaxwind.low_mach",
    "cell_to_faces": "jaxwind.low_mach",
    "conservative_specific_tendency": "jaxwind.low_mach",
    "continuity_residual": "jaxwind.low_mach",
    "dilatation_correction": "jaxwind.low_mach",
    "face_density": "jaxwind.low_mach",
    "mass_flux": "jaxwind.low_mach",
    "mixing_ratio_to_mass_fraction": "jaxwind.low_mach",
    "project_low_mach": "jaxwind.low_mach",
    "build_open_atmospheric_run": "jaxwind.open_abl",
    "build_open_atmospheric_step": "jaxwind.open_abl",
    "InflowPlane": "jaxwind.open_boundary",
    "enforce_open_scalar": "jaxwind.open_boundary",
    "enforce_open_velocity": "jaxwind.open_boundary",
    "extract_inflow_plane": "jaxwind.open_boundary",
    "periodic_to_open_velocity": "jaxwind.open_boundary",
    "validate_inflow_plane": "jaxwind.open_boundary",
    "advection": "jaxwind.numerics.discretization",
    "cell_velocity": "jaxwind.numerics.discretization",
    "courant_number": "jaxwind.numerics.discretization",
    "diffusion": "jaxwind.numerics.discretization",
    "divergence": "jaxwind.numerics.discretization",
    "kinetic_energy": "jaxwind.numerics.discretization",
    "pressure_gradient": "jaxwind.numerics.discretization",
    "stable_timestep": "jaxwind.numerics.discretization",
    "tangential_z_gradient": "jaxwind.numerics.discretization",
    "CLASSICAL_AMG_PCG": "jaxwind.numerics.poisson",
    "PressurePoisson": "jaxwind.numerics.poisson",
    "SparseMatrix": "jaxwind.numerics.poisson",
    "assemble_pressure_matrix": "jaxwind.numerics.poisson",
    "build_amg_solver": "jaxwind.numerics.poisson",
    "build_fft_solver": "jaxwind.numerics.poisson",
    "build_gmg_solver": "jaxwind.numerics.poisson",
    "build_pressure_poisson": "jaxwind.numerics.poisson",
    "default_tolerance": "jaxwind.numerics.poisson",
    "matrix_vector_product": "jaxwind.numerics.poisson",
    "project": "jaxwind.numerics.poisson",
    "CoriolisGeostrophic": "jaxwind.rotation",
    "coriolis_tendency": "jaxwind.rotation",
    "PassiveScalar": "jaxwind.scalar",
    "scalar_tendency": "jaxwind.scalar",
    "AnisotropicMinimumDissipation": "jaxwind.sgs",
    "StaticSmagorinsky": "jaxwind.sgs",
    "eddy_viscosity": "jaxwind.sgs",
    "edge_gradients": "jaxwind.sgs",
    "stress_divergence": "jaxwind.sgs",
    "subfilter_tendency": "jaxwind.sgs",
    "MoninObukhovSurface": "jaxwind.surface",
    "SurfaceExchange": "jaxwind.surface",
    "coupled_surface_exchange": "jaxwind.surface",
    "surface_momentum_tendency": "jaxwind.surface",
    "build_adbem_forcing": "jaxwind.turbine",
    "build_actuator_line_forcing": "jaxwind.turbine",
    "PLANE_MEAN": "jaxwind.sponge",
    "REST": "jaxwind.sponge",
    "rayleigh_sponge_tendency": "jaxwind.sponge",
    "CELL_AVERAGE": "jaxwind.wall",
    "CELL_CENTRE": "jaxwind.wall",
    "LOCAL": "jaxwind.wall",
    "PLANAR": "jaxwind.wall",
    "MoninObukhovWall": "jaxwind.wall",
    "friction_velocity": "jaxwind.wall",
    "logarithmic_profile": "jaxwind.wall",
    "monin_obukhov_boundaries": "jaxwind.wall",
    "sidewall_stress": "jaxwind.wall",
    "sidewall_tendency": "jaxwind.wall",
    "surface_stress": "jaxwind.wall",
    "wall_tendency": "jaxwind.wall",
    "FREE_SLIP": "jaxwind.state",
    "NO_SLIP": "jaxwind.state",
    "OPEN": "jaxwind.state",
    "PERIODIC": "jaxwind.state",
    "Boundaries": "jaxwind.state",
    "StaggeredVelocity": "jaxwind.state",
    "Wall": "jaxwind.state",
    "cell_coordinates": "jaxwind.state",
    "cell_shape": "jaxwind.state",
    "enforce_impermeability": "jaxwind.state",
    "face_coordinates": "jaxwind.state",
    "spanwise_is_periodic": "jaxwind.state",
    "streamwise_is_periodic": "jaxwind.state",
    "validate": "jaxwind.state",
    "x_face_shape": "jaxwind.state",
    "y_face_shape": "jaxwind.state",
    "z_face_shape": "jaxwind.state",
    "zeros": "jaxwind.state",
    "load_case": "jaxwind.config.document",
    "CaseSpec": "jaxwind.config.document",
    "ResolvedCase": "jaxwind.config.document",
    "build_simulation": "jaxwind.simulation.api",
    "Simulation": "jaxwind.simulation.api",
    "RunControls": "jaxwind.simulation.api",
    "AdvanceResult": "jaxwind.simulation.api",
    "run": "jaxwind.runtime.engine",
    "resume": "jaxwind.runtime.engine",
    "RunResult": "jaxwind.runtime.engine"
}

__all__ = sorted(_EXPORTS)


def __getattr__(name):
    if name not in _EXPORTS:
        raise AttributeError(name)
    value = getattr(import_module(_EXPORTS[name]), name)
    globals()[name] = value
    return value
