"""Pressure solvers and interpreter-facing adapters."""

from .distributed_gmg import (
    YSlabConfig,
    YSlabMatrixFreePoissonSolver,
    gather_y_field,
    shard_y_field,
)
from .distributed_mac import (
    YSlabMACProjectionResult,
    YSlabMACProjector,
    YSlabMACVelocity,
    YSlabVelocityPressureProjection,
    gather_y_mac_velocity,
    shard_y_mac_velocity,
)
from .matrix_free_gmg import (
    BoundaryCondition,
    FGMRESConfig,
    FGMRESResult,
    GMGConfig,
    MatrixFreeGMG,
    MatrixFreePoissonOperator,
    MatrixFreePoissonSolver,
    PCGConfig,
    PCGResult,
    PoissonBoundaryConditions,
    RectilinearGrid,
    fgmres,
    pcg,
)
from .mac_projection import (
    _velocity_sum as _velocity_sum,
    VelocityPressureProjection,
    MACProjectionResult,
    MACStageProjector,
    MACVelocity,
    SSPRK3ProjectionResult,
    mac_divergence,
    mac_pressure_gradient,
    projected_ssprk3_step,
    projected_ssprk3_velocity_pressure_step,
    projected_ssprk3_velocity_step,
)

__all__ = [
    "BoundaryCondition",
    "FGMRESConfig",
    "FGMRESResult",
    "GMGConfig",
    "MatrixFreeGMG",
    "MatrixFreePoissonOperator",
    "MatrixFreePoissonSolver",
    "MACProjectionResult",
    "MACStageProjector",
    "MACVelocity",
    "PoissonBoundaryConditions",
    "PCGConfig",
    "PCGResult",
    "RectilinearGrid",
    "SSPRK3ProjectionResult",
    "VelocityPressureProjection",
    "YSlabConfig",
    "YSlabMACProjectionResult",
    "YSlabMACProjector",
    "YSlabMACVelocity",
    "YSlabMatrixFreePoissonSolver",
    "YSlabVelocityPressureProjection",
    "fgmres",
    "pcg",
    "gather_y_field",
    "gather_y_mac_velocity",
    "mac_divergence",
    "mac_pressure_gradient",
    "projected_ssprk3_step",
    "projected_ssprk3_velocity_pressure_step",
    "projected_ssprk3_velocity_step",
    "shard_y_field",
    "shard_y_mac_velocity",
]
